"""Initial Migration

Revision ID: a24e5428fcd5
Revises: 
Create Date: 2024-06-03 09:02:41.980999

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a24e5428fcd5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="insurance",
    )
    op.create_table(
        "policies",
        sa.Column("id", sa.String(length=30), nullable=False),
        sa.Column("amount_insured", sa.Integer(), nullable=False),
        sa.Column("inception_date", sa.String(length=50), nullable=False),
        sa.Column("installment_payment", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["insurance.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="insurance",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("policies", schema="insurance")
    op.drop_table("users", schema="insurance")
    # ### end Alembic commands ###
